# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import calculo_pb2 as calculo__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in calculo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServidorCalculoStub(object):
    """Servicio del Servidor de Cálculo
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalcularMaximo = channel.unary_unary(
                '/calculo.ServidorCalculo/CalcularMaximo',
                request_serializer=calculo__pb2.NumeroLista.SerializeToString,
                response_deserializer=calculo__pb2.NumeroMaximo.FromString,
                _registered_method=True)


class ServidorCalculoServicer(object):
    """Servicio del Servidor de Cálculo
    """

    def CalcularMaximo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServidorCalculoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalcularMaximo': grpc.unary_unary_rpc_method_handler(
                    servicer.CalcularMaximo,
                    request_deserializer=calculo__pb2.NumeroLista.FromString,
                    response_serializer=calculo__pb2.NumeroMaximo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculo.ServidorCalculo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calculo.ServidorCalculo', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServidorCalculo(object):
    """Servicio del Servidor de Cálculo
    """

    @staticmethod
    def CalcularMaximo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculo.ServidorCalculo/CalcularMaximo',
            calculo__pb2.NumeroLista.SerializeToString,
            calculo__pb2.NumeroMaximo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ServidorOperacionStub(object):
    """Servicio de los Servidores de Operación
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObtenerMaximo = channel.unary_unary(
                '/calculo.ServidorOperacion/ObtenerMaximo',
                request_serializer=calculo__pb2.NumeroLista.SerializeToString,
                response_deserializer=calculo__pb2.NumeroMaximo.FromString,
                _registered_method=True)


class ServidorOperacionServicer(object):
    """Servicio de los Servidores de Operación
    """

    def ObtenerMaximo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServidorOperacionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObtenerMaximo': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerMaximo,
                    request_deserializer=calculo__pb2.NumeroLista.FromString,
                    response_serializer=calculo__pb2.NumeroMaximo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculo.ServidorOperacion', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calculo.ServidorOperacion', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServidorOperacion(object):
    """Servicio de los Servidores de Operación
    """

    @staticmethod
    def ObtenerMaximo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculo.ServidorOperacion/ObtenerMaximo',
            calculo__pb2.NumeroLista.SerializeToString,
            calculo__pb2.NumeroMaximo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
